name: Conditional_Events_Example

on:
  push:
    branches:
      - 'feature/**'
      - 'main'
  pull_request:
    branches: [ $default-branch ]

jobs:
  Check1:
    if: ${{github.repository == 'octo-org/octo-repo-prod'}} # this will evaluate to false
    runs-on: ubuntu-latest
    steps:
      - name: Echo Basic Information
        run: |
          "Ref: $GITHUB_REF" >> ./basic_info.txt
          "Job Id: $GITHUB_JOB" >> ./basic_info.txt
          "Action: $GITHUB_ACTION" >> ./basic_info.txt
          "Actor: $GITHUB_ACTOR" >> ./basic_info.txt
          cat ./basic_info.txt
  Check2:
    if: ${{github.repository != 'octo-org/octo-repo-prod'}} # this will evaluate to true
    runs-on: ubuntu-latest
    steps:
      - name: Echo Basic Information
        run: |
          "Ref: $GITHUB_REF" >> ./basic_info.txt
          "Job Id: $GITHUB_JOB" >> ./basic_info.txt
          "Action: $GITHUB_ACTION" >> ./basic_info.txt
          "Actor: $GITHUB_ACTOR" >> ./basic_info.txt
          cat ./basic_info.txt
  Check3:
    if: ${{github.repository == 'xenon-92/smotw'}} # this will evaluate to true
    runs-on: ubuntu-latest
    needs: [Check2]
    steps:
      - name: Echo Basic Information
        run: |
          ls -la > ./file_list.txt
          cat ./file_list.txt