name: CI pipeline

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  sayHello:
    runs-on: 'ubuntu-latest'

    steps:
      - name: bash to compute
        run: |
          echo "just saying hi"
          ls -la > ./rough
          cat ./rough
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: build solution
        run: go build -v ./...