name: sayHello

on:
  push:
    branches:
      - 'feature/**'
      - 'main'

jobs:
  sayHello:
    runs-on: 'ubuntu-latest'

    steps:
      - name: bash to compute
        run: |
          echo "just saying hi"
          ls -la > ./rough
          cat ./rough